# Generated by Django 4.1.6 on 2023-02-03 01:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eenie_meenie', '0002_remove_user_name_pool_remove_user_name_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name_pool',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='name_ranking',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
