# Generated by Django 4.1.6 on 2023-02-15 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eenie_meenie', '0005_alter_user_name_pool_alter_user_name_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='partner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnered_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
