# Generated by Django 4.1.6 on 2023-02-17 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eenie_meenie', '0006_remove_user_following_user_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partnered_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
