# Generated by Django 4.1.6 on 2023-02-07 23:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eenie_meenie', '0004_setting_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name_pool',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='name_ranking',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None),
        ),
    ]
